[2016-08-31 00:29:57,125] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:29:57,131] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--fawn, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=fawn (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03821A50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:29:57,138] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:29:57,140] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--headband, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=headband (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03771530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:29:57,142] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:29:57,144] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--wrought-iron, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=wrought-iron (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03771710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:32:22,470] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:32:22,733] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /dict/search?q=fawn HTTP/1.1" 200 41431
[2016-08-31 00:32:22,927] [DEBUG] [Anki.py] [Anki] [do_request] Download word path D:\GitHub\AnkiAddon\testProject\Import_path\fawn
[2016-08-31 00:32:24,839] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): dict.youdao.com
[2016-08-31 00:32:24,946] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /example/mdia/audio/fawn HTTP/1.1" 200 None
[2016-08-31 00:32:24,984] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:32:25,210] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /dict/search?q=headband HTTP/1.1" 200 39804
[2016-08-31 00:32:25,388] [DEBUG] [Anki.py] [Anki] [do_request] Download word path D:\GitHub\AnkiAddon\testProject\Import_path\headband
[2016-08-31 00:32:26,369] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): dict.youdao.com
[2016-08-31 00:32:26,440] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /example/mdia/audio/headband HTTP/1.1" 200 None
[2016-08-31 00:32:26,477] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:32:26,717] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /dict/search?q=wrought-iron HTTP/1.1" 200 37537
[2016-08-31 00:32:26,846] [DEBUG] [Anki.py] [Anki] [do_request] Download word path D:\GitHub\AnkiAddon\testProject\Import_path\wrought-iron
[2016-08-31 00:32:28,276] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): dict.youdao.com
[2016-08-31 00:32:28,351] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /example/mdia/audio/wrought-iron HTTP/1.1" 200 None
[2016-08-31 00:32:28,390] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:32:28,618] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /dict/search?q=foul HTTP/1.1" 200 45757
[2016-08-31 00:32:29,006] [DEBUG] [Anki.py] [Anki] [do_request] Download word path D:\GitHub\AnkiAddon\testProject\Import_path\foul
[2016-08-31 00:32:29,865] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): dict.youdao.com
[2016-08-31 00:32:29,940] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /example/mdia/audio/foul HTTP/1.1" 200 None
[2016-08-31 00:32:30,151] [DEBUG] [Anki.py] [Anki] [do_request] Download http://dict.youdao.com/pureaudio?docid=-927169759615584735
[2016-08-31 00:32:30,285] [DEBUG] [Anki.py] [Anki] [do_request] Download http://dict.youdao.com/pureaudio?docid=-7716596945342253764
[2016-08-31 00:32:30,400] [DEBUG] [Anki.py] [Anki] [do_request] Download http://dict.youdao.com/pureaudio?docid=-1168927721854527503
[2016-08-31 00:32:30,494] [DEBUG] [Anki.py] [Anki] [do_request] Download http://dict.youdao.com/pureaudio?docid=7986250766614511610
[2016-08-31 00:32:30,651] [DEBUG] [Anki.py] [Anki] [do_request] Download http://dict.youdao.com/pureaudio?docid=3740634339837337658
[2016-08-31 00:32:30,654] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): dict.youdao.com
[2016-08-31 00:32:30,739] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /example/auth/foul HTTP/1.1" 200 None
[2016-08-31 00:32:32,411] [DEBUG] [Anki.py] [Anki] [do_request] Download http://www.forbes.com/forbes/2010/1206/investment-guide-living-will-software-cheap-estate-planning.html?partner=email
[2016-08-31 00:32:34,282] [DEBUG] [Anki.py] [Anki] [do_request] Download http://www.forbes.com/sites/jennagoudreau/2010/10/21/gqs-glee-photos-exploit-young-women/print/
[2016-08-31 00:32:34,503] [ERROR] [Anki.py] [Anki] [do_request] Exception happened, can't download mp3:(What bearing does all this history have on the foul events unfolding right now in Gaza? 
            					  		    					
)(http://www.economist.com/node/12899483/email?page=33).
Exception:[Errno socket error] [Errno 10054] 
[2016-08-31 00:32:35,721] [DEBUG] [Anki.py] [Anki] [do_request] Download http://www.npr.org/templates/story/story.php?storyId=186985960
[2016-08-31 00:32:36,726] [DEBUG] [Anki.py] [Anki] [do_request] Download http://news.bbc.co.uk/sport2/mobile/cricket/england/8886554.stm
[2016-08-31 00:32:36,729] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:32:36,990] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /dict/search?q=circuitry HTTP/1.1" 200 39645
[2016-08-31 00:32:37,190] [DEBUG] [Anki.py] [Anki] [do_request] Download word path D:\GitHub\AnkiAddon\testProject\Import_path\circuitry
[2016-08-31 00:32:37,674] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): dict.youdao.com
[2016-08-31 00:32:37,750] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /example/mdia/audio/circuitry HTTP/1.1" 200 None
[2016-08-31 00:32:37,986] [DEBUG] [Anki.py] [Anki] [do_request] Download http://dict.youdao.com/pureaudio?docid=-1166344550247529391
[2016-08-31 00:32:37,990] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): dict.youdao.com
[2016-08-31 00:32:38,075] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /example/auth/circuitry HTTP/1.1" 200 None
[2016-08-31 00:32:39,466] [DEBUG] [Anki.py] [Anki] [do_request] Download http://www.forbes.com/2002/05/15/0515alzheimers.html
[2016-08-31 00:32:42,858] [DEBUG] [Anki.py] [Anki] [do_request] Download http://www.newyorker.com/reporting/2009/05/18/090518fa_fact_lehrer?currentPage=all
[2016-08-31 00:33:03,154] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:33:03,408] [DEBUG] [connectionpool.py] [connectionpool] [_make_request] "GET /dict/search?q=jihad HTTP/1.1" 200 39748
[2016-08-31 00:33:03,884] [DEBUG] [Anki.py] [Anki] [do_request] Download word path D:\GitHub\AnkiAddon\testProject\Import_path\jihad
[2016-08-31 00:33:23,960] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:33:23,969] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--aegis, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=aegis (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03538AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:33:23,974] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:33:23,976] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--preface, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=preface (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x034865D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:33:23,979] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:33:23,983] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--woody, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=woody (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x034867D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:34:14,252] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:34:14,266] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--aegis, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=aegis (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03A8A350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:34:18,131] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:34:18,141] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--preface, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=preface (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03A8AD70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:34:21,140] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:34:21,151] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--woody, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=woody (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03A8AF70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:34:59,279] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:34:59,285] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--aegis, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=aegis (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x032F5AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:34:59,290] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:34:59,292] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--preface, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=preface (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0323F5D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[2016-08-31 00:34:59,295] [INFO] [connectionpool.py] [connectionpool] [_new_conn] Starting new HTTP connection (1): cn.bing.com
[2016-08-31 00:34:59,296] [ERROR] [Anki.py] [Anki] [import_words] Can't get Word--woody, exception happened.
Traceback (most recent call last):
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 296, in import_words
    do_request(word)
  File "D:/GitHub/AnkiAddon/testProject/Anki.py", line 77, in do_request
    source_code = requests.get(Anki_common.word_url(word), headers=random.choice(headers))
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cn.bing.com', port=80): Max retries exceeded with url: /dict/search?q=woody (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0323F7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
